# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d195bc54999e4f30db510373bfb1cd17c636ac448d2f333829360a0c517c5bfdf170f1b1ba1b9a7455ea6d0ccb90a049af76320f99e91f2b0383a7c17111965

test:
  secret_key_base: f7970730b2b7f2cf1e73a520775448da8ccd97aa4516a62a9ee5dbbeddf8238894c831a6968badf4426a0432465820d65de8e099485d2edcd292f974eeb90ff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
